### 1. Array Creation and Basic Operations
1. **Create a 1D array of the first 10 positive integers.**
   - Print the array.
   - Find the sum of all elements in the array.
   - Calculate the mean of the elements.

2. **Create a 2D array of shape (3, 4) with random integers between 1 and 10.**
   - Print the array.
   - Find the maximum and minimum values in the array.
   - Calculate the sum of each row and each column.

### 2. Array Indexing and Slicing
3. **Create a 1D array of 20 random integers between 1 and 100.**
   - Print the array.
   - Print the elements from index 5 to 15.
   - Print every second element of the array.

4. **Create a 2D array of shape (5, 5) with random integers between 1 and 50.**
   - Print the array.
   - Extract and print the second row.
   - Extract and print the third column.
   - Extract and print a 3x3 subarray from the original array.

### 3. Array Manipulation
5. **Create two 1D arrays of 10 random integers each.**
   - Concatenate the two arrays.
   - Sort the concatenated array.
   - Find the unique elements in the concatenated array.

6. **Create a 2D array of shape (4, 4) with random integers between 1 and 20.**
   - Print the array.
   - Flatten the array into a 1D array.
   - Reshape the flattened array back into a 2D array of shape (2, 8).

### 4. Mathematical and Statistical Operations
7. **Create a 1D array of 15 random integers between 1 and 50.**
   - Print the array.
   - Calculate and print the standard deviation of the array.
   - Find and print the index of the maximum value in the array.
   - Normalize the array (scale the values to a range between 0 and 1).

8. **Create two 2D arrays of shape (3, 3) with random integers between 1 and 10.**
   - Print both arrays.
   - Perform element-wise addition, subtraction, and multiplication of the arrays.
   - Calculate the dot product of the arrays.


In [ ]:
#Create a 1D array of the first 10 positive integers.

import numpy as np

# Create the 1D array of the first 10 positive integers
array = np.arange(1, 11)

# Print the array
print("Array:", array)

# Find the sum of all elements in the array
sum_of_elements = np.sum(array)
print("Sum of elements:", sum_of_elements)

# Calculate the mean of the elements
mean_of_elements = np.mean(array)
print("Mean of elements:", mean_of_elements)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Sum of elements: 55
Mean of elements: 5.5


In [ ]:
#Create a 2D array of shape (3, 4) with random integers between 1 and 10.

import numpy as np

# Create the 2D array with random integers between 1 and 10
array_2d = np.random.randint(1, 11, size=(3, 4))

# Print the array
print("2D Array:\n", array_2d)

# Find the maximum value in the array
max_value = np.max(array_2d)
print("Maximum value:", max_value)

# Find the minimum value in the array
min_value = np.min(array_2d)
print("Minimum value:", min_value)

# Calculate the sum of each row
sum_of_rows = np.sum(array_2d, axis=1)
print("Sum of each row:", sum_of_rows)

# Calculate the sum of each column
sum_of_columns = np.sum(array_2d, axis=0)
print("Sum of each column:", sum_of_columns)


2D Array:
 [[ 1  4  8  6]
 [10 10  6  3]
 [ 4  3  1  3]]
Maximum value: 10
Minimum value: 1
Sum of each row: [19 29 11]
Sum of each column: [15 17 15 12]


In [ ]:
#Create a 2D array of shape (3, 4) with random integers between 1 and 10.
import numpy as np
# Create the 1D array with 20 random integers between 1 and 100
array_1d = np.random.randint(1, 101, size=20)

#print the array
print("1D array:",array_1d)
# Print the elements from index 5 to 15
elements_5_to_15 = array_1d[5:16]
print("Elements from index 5 to 15:", elements_5_to_15)
# Print every second element of the array
every_second_element = array_1d[::2]
print("Every second element:", every_second_element)

1D array: [55 28 75 67 63 11  2 25 24 65 45 73 69 67 22 26 88  4 66 75]
Elements from index 5 to 15: [11  2 25 24 65 45 73 69 67 22 26]
Every second element: [55 75 63  2 24 45 69 22 88 66]


In [ ]:
#Create a 1D array of 20 random integers between 1 and 100.

import numpy as np

# Create a 1D array of 20 random integers between 1 and 100
random_array = np.random.randint(1, 101, 20)

# Print the array
print("Array:", random_array)

# Print the elements from index 5 to 15
print("Elements from index 5 to 15:", random_array[5:16])

# Print every second element of the array
print("Every second element of the array:", random_array[::2])



Array: [  9  14  82   3  87  39  64  43   2  31  85 100  21  11  28  27  70  58
  10  65]
Elements from index 5 to 15: [ 39  64  43   2  31  85 100  21  11  28  27]
Every second element of the array: [ 9 82 87 64  2 85 21 28 70 10]


In [ ]:


# Create two 1D arrays of 10 random integers each
array1 = np.random.randint(1, 101, size=10)
array2 = np.random.randint(1, 101, size=10)

# Concatenate the two arrays
concatenated_array = np.concatenate((array1, array2))

# Sort the concatenated array
sorted_array = np.sort(concatenated_array)

# Find the unique elements in the concatenated array
unique_elements = np.unique(concatenated_array)

array1, array2, concatenated_array, sorted_array, unique_elements


NameError: name 'np' is not defined